### PR TITLE
Fixes old Tegustation in the list

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About this Pull Request

Old Tegustation was a downstream of Fulpstation, as seen in https://github.com/vlggms/tegustation/pull/9

### CODE REVIEW

**Comment by EgorDinamit** [comment]
You might've misunderstood what "downstream" means.
Everything that resembled FulpStation has been thoroughly removed ever since we forked new(by that time) /tg/station codebase.

TeguStation was always a /tg/station downstream with very limited pick of FulpStation features.

**Comment by JohnFulpWillard** [comment]
> You might've misunderstood what "downstream" means. Everything that resembled FulpStation has been thoroughly removed ever since we forked new(by that time) /tg/station codebase.
> 
> TeguStation was always a /tg/station downstream with very limited pick of FulpStation features.

You started off of fulp then updated to latest TG through that, you're still a Fulp downstream because that's what you branched off of. That's the whole reason why https://github.com/vlggms/fulpstation was a thing in the first place.

**Comment by EgorDinamit** [comment]
> You started off of fulp then updated to latest TG through that, you're still a Fulp downstream because that's what you branched off of. That's the whole reason why https://github.com/vlggms/fulpstation was a thing in the first place.

Nope. We did it exactly the other way around, picked a newer /tg/ branch and added some Fulp features ontop of it.
We've always been /tg/ fork while Fulp was still running on a heavily outdated and broken code.

**Comment by EgorDinamit** [comment]
You really are shooting yourself in the leg here.
image

**Pull request closed without merging**
