### PR TITLE
More up to date summary

### PR DESCRIPTION
**Pull request by Muolai**
Stole the files from one of the PR's and added a couple more servers to ss14

### CODE REVIEW

**Comment by ZeWaka** [comment]
sure

**Comment by Muolai** [comment]
Is the e-mail right now?

**Comment by ZeWaka** [comment]
> Is the e-mail right now?

Yes, but it's technically still in the commit history. You'd have to overwrite it. However, it won't be visible in the main commit history - only for people who look at this PR.

**Comment by Muolai** [comment]
yeah, then delete it

**Comment by ZeWaka** [comment]
I'll have to ask GitHub Support.

**Pull request closed without merging**
