### PR TITLE
Add Bee forks and SS14 forks

### LINKED ISSUE #16: Missing major SS14 codebases.
Needs to include Corvax (long running full russian translation of the base game) and Nyanotrasen (??? i'm not sure what they're doing but it's funky)

Both regularly hit 50 players.

Not sure how to best organize these in the graph as it seems to draw them weird if I simply try and add them.

### PR DESCRIPTION
**Pull request by itsmeow**
Bee
- RoyaleStation
- SinguloStation
- MonkeStation

SS14 (Closes #16)
- Corvax
- Nyanotrasen

Also updates README and removes the "Circa Mid 2021", it's not very helpful to include

### CODE REVIEW

**Comment by ZeWaka** [comment]
The SS14 additions look terrible, I think those need to be fixed.

**Comment by itsmeow** [comment]
I'm not familiar with DOT so I don't know how to change how it generates the subbox

**Comment by itsmeow** [comment]
Fixed

**Comment by ZeWaka** [comment]
kinda gross but whatever lol

**Pull request merged**
